import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; 
import Header from "../components/Header";
import FooterSection from "../components/FooterSection";
import { ModalProvider } from "../contexts/ModalContext";
import { LanguageProvider } from "../contexts/LanguageContext";
import ModalWrapper from "../components/ModalWrapper";

const airbnbCereal = localFont({
  src: [
    { path: "../fonts/AirbnbCereal_W_Bd.otf", weight: "400", style: "normal" },
    { path: "../fonts/AirbnbCereal_W_Bk.otf", weight: "500", style: "normal" },
    { path: "../fonts/AirbnbCereal_W_Blk.otf", weight: "700", style: "normal" },
  ],
  variable: "--font-airbnb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${airbnbCereal.variable} antialiased`}>
        <LanguageProvider>
          <ModalProvider>
            <Header />
            <main className="pt-0">
              {children}
            </main>
            <FooterSection />
            <ModalWrapper />
          </ModalProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
